### ISSUE TITLE
FairMiner.cpp:24: Avoid 31bit lock

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/selfish#38]
The puzzle `16-01009a96` from #16 has to be resolved:

https://github.com/DronMDF/selfish/blob/16e7e1761bd31635355d315292c96cb803d85684/FairMiner.cpp#L24-L24

The puzzle was created by Andrey Valyaev on 08-May-18. 

Estimate: 0 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
This is affetc to #12 

Difficulty: 9
586:d2fd21dc**000**5a2e2@72c21b4a00565da0 by Bob
Amount: Alice: 192, Bob: 203, Pavel: 191, 

difficulty map inside a hash string...

**Comment by 0pdd** [comment]
The puzzle `16-01009a96` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#49](https://github.com/DronMDF/selfish/issues/49) is still not solved.
