### ISSUE TITLE
Application skeleton

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/selfish#7]
class Chain for keep chained blocks with forks
class Miner for new block generation
Main cycle call miner for propogate chain.

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#10](https://github.com/DronMDF/selfish/issues/10), [#9](https://github.com/DronMDF/selfish/issues/9) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#12](https://github.com/DronMDF/selfish/issues/12), [#13](https://github.com/DronMDF/selfish/issues/13), [#9](https://github.com/DronMDF/selfish/issues/9) are still not solved; solved: [#10](https://github.com/DronMDF/selfish/issues/10).

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#12](https://github.com/DronMDF/selfish/issues/12), [#9](https://github.com/DronMDF/selfish/issues/9) are still not solved; solved: [#10](https://github.com/DronMDF/selfish/issues/10), [#13](https://github.com/DronMDF/selfish/issues/13).

**Comment by 0pdd** [comment]
@DronMDF 4 puzzles [#12](https://github.com/DronMDF/selfish/issues/12), [#21](https://github.com/DronMDF/selfish/issues/21), [#22](https://github.com/DronMDF/selfish/issues/22), [#23](https://github.com/DronMDF/selfish/issues/23) are still not solved; solved: [#10](https://github.com/DronMDF/selfish/issues/10), [#13](https://github.com/DronMDF/selfish/issues/13), [#9](https://github.com/DronMDF/selfish/issues/9).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#12](https://github.com/DronMDF/selfish/issues/12), [#22](https://github.com/DronMDF/selfish/issues/22), [#23](https://github.com/DronMDF/selfish/issues/23) are still not solved; solved: [#10](https://github.com/DronMDF/selfish/issues/10), [#13](https://github.com/DronMDF/selfish/issues/13), [#21](https://github.com/DronMDF/selfish/issues/21), [#9](https://github.com/DronMDF/selfish/issues/9).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#12](https://github.com/DronMDF/selfish/issues/12), [#22](https://github.com/DronMDF/selfish/issues/22), [#26](https://github.com/DronMDF/selfish/issues/26) are still not solved; solved: [#10](https://github.com/DronMDF/selfish/issues/10), [#13](https://github.com/DronMDF/selfish/issues/13), [#21](https://github.com/DronMDF/selfish/issues/21), [#23](https://github.com/DronMDF/selfish/issues/23), [#9](https://github.com/DronMDF/selfish/issues/9).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#12](https://github.com/DronMDF/selfish/issues/12), [#22](https://github.com/DronMDF/selfish/issues/22), [#28](https://github.com/DronMDF/selfish/issues/28) are still not solved; solved: [#10](https://github.com/DronMDF/selfish/issues/10), [#13](https://github.com/DronMDF/selfish/issues/13), [#21](https://github.com/DronMDF/selfish/issues/21), [#23](https://github.com/DronMDF/selfish/issues/23), [#26](https://github.com/DronMDF/selfish/issues/26), [#9](https://github.com/DronMDF/selfish/issues/9).

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#12](https://github.com/DronMDF/selfish/issues/12), [#22](https://github.com/DronMDF/selfish/issues/22) are still not solved; solved: [#10](https://github.com/DronMDF/selfish/issues/10), [#13](https://github.com/DronMDF/selfish/issues/13), [#21](https://github.com/DronMDF/selfish/issues/21), [#23](https://github.com/DronMDF/selfish/issues/23), [#26](https://github.com/DronMDF/selfish/issues/26), [#28](https://github.com/DronMDF/selfish/issues/28), [#30](https://github.com/DronMDF/selfish/issues/30), [#9](https://github.com/DronMDF/selfish/issues/9).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#22](https://github.com/DronMDF/selfish/issues/22), [#43](https://github.com/DronMDF/selfish/issues/43), [#44](https://github.com/DronMDF/selfish/issues/44) are still not solved; solved: [#10](https://github.com/DronMDF/selfish/issues/10), [#12](https://github.com/DronMDF/selfish/issues/12), [#13](https://github.com/DronMDF/selfish/issues/13), [#21](https://github.com/DronMDF/selfish/issues/21), [#23](https://github.com/DronMDF/selfish/issues/23), [#26](https://github.com/DronMDF/selfish/issues/26), [#28](https://github.com/DronMDF/selfish/issues/28), [#30](https://github.com/DronMDF/selfish/issues/30), [#9](https://github.com/DronMDF/selfish/issues/9).

**Comment by 0pdd** [comment]
@DronMDF 4 puzzles [#44](https://github.com/DronMDF/selfish/issues/44), [#46](https://github.com/DronMDF/selfish/issues/46), [#51](https://github.com/DronMDF/selfish/issues/51), [#52](https://github.com/DronMDF/selfish/issues/52) are still not solved; solved: [#10](https://github.com/DronMDF/selfish/issues/10), [#12](https://github.com/DronMDF/selfish/issues/12), [#13](https://github.com/DronMDF/selfish/issues/13), [#21](https://github.com/DronMDF/selfish/issues/21), [#22](https://github.com/DronMDF/selfish/issues/22), [#23](https://github.com/DronMDF/selfish/issues/23), [#26](https://github.com/DronMDF/selfish/issues/26), [#28](https://github.com/DronMDF/selfish/issues/28), [#30](https://github.com/DronMDF/selfish/issues/30), [#43](https://github.com/DronMDF/selfish/issues/43), [#9](https://github.com/DronMDF/selfish/issues/9).

**Comment by 0pdd** [comment]
@DronMDF 4 puzzles [#44](https://github.com/DronMDF/selfish/issues/44), [#46](https://github.com/DronMDF/selfish/issues/46), [#52](https://github.com/DronMDF/selfish/issues/52), [#64](https://github.com/DronMDF/selfish/issues/64) are still not solved; solved: [#10](https://github.com/DronMDF/selfish/issues/10), [#12](https://github.com/DronMDF/selfish/issues/12), [#13](https://github.com/DronMDF/selfish/issues/13), [#21](https://github.com/DronMDF/selfish/issues/21), [#22](https://github.com/DronMDF/selfish/issues/22), [#23](https://github.com/DronMDF/selfish/issues/23), [#26](https://github.com/DronMDF/selfish/issues/26), [#28](https://github.com/DronMDF/selfish/issues/28), [#30](https://github.com/DronMDF/selfish/issues/30), [#43](https://github.com/DronMDF/selfish/issues/43), [#51](https://github.com/DronMDF/selfish/issues/51), [#9](https://github.com/DronMDF/selfish/issues/9).

**Comment by 0pdd** [comment]
@DronMDF 4 puzzles [#44](https://github.com/DronMDF/selfish/issues/44), [#46](https://github.com/DronMDF/selfish/issues/46), [#64](https://github.com/DronMDF/selfish/issues/64), [#66](https://github.com/DronMDF/selfish/issues/66) are still not solved; solved: [#10](https://github.com/DronMDF/selfish/issues/10), [#12](https://github.com/DronMDF/selfish/issues/12), [#13](https://github.com/DronMDF/selfish/issues/13), [#21](https://github.com/DronMDF/selfish/issues/21), [#22](https://github.com/DronMDF/selfish/issues/22), [#23](https://github.com/DronMDF/selfish/issues/23), [#26](https://github.com/DronMDF/selfish/issues/26), [#28](https://github.com/DronMDF/selfish/issues/28), [#30](https://github.com/DronMDF/selfish/issues/30), [#43](https://github.com/DronMDF/selfish/issues/43), [#51](https://github.com/DronMDF/selfish/issues/51), [#52](https://github.com/DronMDF/selfish/issues/52), [#9](https://github.com/DronMDF/selfish/issues/9).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#44](https://github.com/DronMDF/selfish/issues/44), [#46](https://github.com/DronMDF/selfish/issues/46), [#64](https://github.com/DronMDF/selfish/issues/64) are still not solved; solved: [#10](https://github.com/DronMDF/selfish/issues/10), [#12](https://github.com/DronMDF/selfish/issues/12), [#13](https://github.com/DronMDF/selfish/issues/13), [#21](https://github.com/DronMDF/selfish/issues/21), [#22](https://github.com/DronMDF/selfish/issues/22), [#23](https://github.com/DronMDF/selfish/issues/23), [#26](https://github.com/DronMDF/selfish/issues/26), [#28](https://github.com/DronMDF/selfish/issues/28), [#30](https://github.com/DronMDF/selfish/issues/30), [#43](https://github.com/DronMDF/selfish/issues/43), [#51](https://github.com/DronMDF/selfish/issues/51), [#52](https://github.com/DronMDF/selfish/issues/52), [#66](https://github.com/DronMDF/selfish/issues/66), [#9](https://github.com/DronMDF/selfish/issues/9).
